### ISSUE TITLE
exception thrown on closing game while still in character select

### ISSUE THREAD

**Issue by Nimac0** [Nimac0/SDL_Minigame#26]
clicking on the x to close the window and then on the popup 'q' to quit, the programm throws an exception (access violation)
possible cause:
exception is thrown in refresh player function in game.cpp, probably cant handle if no player position exists (since on the select screen the players position hasnt been set yet
possible solutions:
- change entire popup thing as it isnt ideal anyway
- look into why its even being called in the first place if players havent been set yet
- add early return or other handling if posistion/player dont exist yet

**Comment by Nanogamer7** [comment]
Issue caused by implementation for #9, as that will be reverted this can be closed
