### ISSUE TITLE
Separating game-dev code from engine code - 1

### ISSUE THREAD

**Issue by Nimac0** [Nimac0/SDL_Minigame#28]
Starting point:
take out update() and init() from game.cpp into its own cpp
-> goal is that there is a folder with everything we've programmed so far named 'engine' and one folder containing only the cpp titled 'dev'
-> this new cpp has the same accesses as the original one (use same game.h) so all functions from engine are accessible
-> there will be errors as there are some globals conflicting (see issue about fixing globals)
-> once it is fixed in a way that it runs again as usual despite the refactor/split move on to step two of splitting (other issue)

**Comment by Nanogamer7** [comment]
Depends on #27

**Comment by Nimac0** [comment]
is done
