### ISSUE TITLE
Separating game-dev code from engine code - 2

### ISSUE THREAD

**Issue by Nimac0** [Nimac0/SDL_Minigame#29]
try moving parts of chicken game step by step, make note of parts that break the program when moved
(-> those are parts that are not properly split, need further issues)
end goal is to have no chicken game specific content in engine folder, but still have the game function as usual just with different location
the following files specifically could/need to be altered:
- [x] AssetManager.cpp -> calculateSpawnposition(), -> calculateType()
- [x] ColliderComponent.cpp -> in init() there is something about the projectiles (sidenote ColliderComponent::handleCollision() might be deprecated since collisionhandler.cpp exists)
- [x] #35
- [x] #38
- [x] #32 
- [x] #36
- [x] #40
- [x] SoundManager.cpp ->playSound() is a hardcoded switch maybe make dictionary/map instead
- [x] #39
- [x] #37

**Comment by Nanogamer7** [comment]
Depends on #28

**Comment by Nanogamer7** [comment]
Define dev more concrete, seems to mean end user or game dev in context

**Comment by Nanogamer7** [comment]
"Moving the game parts" should probably mean a separate repository
