### ISSUE TITLE
KeyboardController manages too much functionality

### ISSUE THREAD

**Issue by Nanogamer7** [Nimac0/SDL_Minigame#32]
Keyboard controller currently handles these functions:
- Input mapping
- Input events
  - Associated player actions (walk, fire)
  - Sprite directions and animations
  - Sound events

Furthermore keyboard controller does not support different input methods (keyboard vs controller).

---

A potential solution for the latter problem would be an input event handler, using `SDL_Event` to parse input events through an abstraction layer, which intern provides access to player components. The abstraction layer could be implemented as for example a bitset, which however would limit movement directions to 45° intervals, or via a struct storing input values as generic booleans/integers. The second example would also provide an easy way to map inputs, as the addresses of the struct members could be mapped to input events, but does not yet provide an implementations to assign the mapping in the first place.

To solve the clutter in the keyboard controller, the existing functionality would need to be moved into separate components, but should be relatively easy if components can pull current status of controls from a struct assigned to the entity/player

TODO list if going with suggested solution:

- [ ] Input event handler
- [ ] Input state struct -> could store directly in all entities (struct or nullptr), or in an input component
- [ ] Movement handling -> either separate component or integrated with transform component (e.g. condition "not nullptr"/"has input component")
- [ ] Sound events -> sound component pulling from input component would be too specific, needs more flexible solution to allow other entities to have sound
- [ ] Sprite condition -> could be pulled from transform component (e.g. condition "velocity not zero")
- [ ] Input assignment
- [ ] Input switching -> solution to solve assignment and switching: if controllers are detected, use those, otherwise keyboard input; alternatively allow for more players
- [ ] main menu navigation with controllers
- [ ] input prompts for controllers

**Comment by Nimac0** [comment]
deprecated
