### ISSUE TITLE
TextureMap alternative to strings

### ISSUE THREAD

**Issue by Nimac0** [Nimac0/SDL_Minigame#62]
- currently both sound and animation gets loaded using a string passed as a parameter, try to rework it more elegantly i.e. using a hashmap to load the assets in (if it makes sense).
- move sound implementation to chickengame

**Comment by Nimac0** [comment]
Maybe extern Enum -> int as key in engine

**Comment by Freezarite** [comment]
TextureManager changes were bigger as expected, therefore changes to SoundManager and AnimationManager are going to be moved to their own tickets.
