### ISSUE TITLE
Generalize helper functions

### ISSUE THREAD

**Issue by Nanogamer7** [Nimac0/SDL_Minigame#71]
Some functions like AssetManager::calculateSpawnPosition() were originally just a helper function for one single use case, but probably have more than one use case. This needs to be evaluated for each helper function individually. Furthermore, helper functions that can be reused also need to be documented, and helper functions that cannot be reused should be set private.

**Comment by ineslelin** [comment]
found only one other helper function that could have multiple use cases during my search, calculateType() in AssetManager. It's used specifically for Powerups, but could probably also be used for other items or entities
