### ISSUE TITLE
Add flexible render order

### ISSUE THREAD

**Issue by Nanogamer7** [Nimac0/SDL_Minigame#81]
The render order is currently defined by a hard-coded order of list:
https://github.com/VEGO-Engine/Engine/blob/e493960fe0c1107662df6446f2f8a12cae27f681/src/GameInternal.cpp#L169-L188
This is sub-optimal, as it restricts the game dev to use our defined groups for objects, and they are always in the same fixed order. A better approach would be to either allow arbitrary orders, perhaps using a z-index.

**Comment by Nanogamer7** [comment]
Required for #53

**Comment by ineslelin** [comment]
Yeah, z-index seems pretty useful for that if i understood it correctly
